export { ClinicaSection } from "./clinica-section"
export { ProcedimentosSection } from "./procedimentos-section"
export { CamposSection } from "./campos-section"
export { TeamSection } from "./team-section"
export { AgendasSection } from "./agendas-section"
export { AparenciaSection } from "./aparencia-section"
export { PlanoSection } from "./plano-section"
